/* eslint-disable */
/* global WebImporter */
/**
 * Parser for accordion-faq.
 * Base: accordion (2 columns; first row block name, each subsequent row = 1 item).
 * Source: wknd.site accordion (div.accordion.panelcontainer > .cmp-accordion).
 * Generated by import-parser sub-agent.
 *
 * Library structure (Accordion):
 *   Cell 1: Title (clickable label)
 *   Cell 2: Content (body of the panel)
 */
export default function parse(element, { document }) {
  const items = Array.from(element.querySelectorAll('.cmp-accordion__item'));

  const cells = [];
  items.forEach((item) => {
    const titleEl = item.querySelector('.cmp-accordion__title, .cmp-accordion__header');
    const panel = item.querySelector('.cmp-accordion__panel');

    const title = titleEl ? (titleEl.textContent || '').trim() : '';

    // Content cell: pull the meaningful text container from the panel.
    let contentCell = '';
    if (panel) {
      const textEl = panel.querySelector('.cmp-text');
      if (textEl) {
        contentCell = Array.from(textEl.children).length
          ? Array.from(textEl.children)
          : (textEl.textContent || '').trim();
      } else {
        contentCell = panel;
      }
    }

    if (title || (contentCell && contentCell.length !== 0)) {
      cells.push([title, contentCell]);
    }
  });

  // Empty-block guard.
  if (cells.length === 0) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'accordion-faq', cells });
  element.replaceWith(block);
}
