/* eslint-disable */
/* global WebImporter */
/**
 * Parser for breadcrumbs.
 * Base: breadcrumbs (custom block — structure inferred from source HTML).
 * Source: wknd.site adventure/magazine pages (div.breadcrumb ... nav.cmp-breadcrumb).
 * Generated by import-parser sub-agent.
 *
 * Content model: one row per crumb, single cell each. Ancestor crumbs contain a
 * link; the current/active page is plain text. The block JS treats the last row
 * as the active page.
 */
export default function parse(element, { document }) {
  // Breadcrumb items live in the cmp-breadcrumb ordered list.
  const items = Array.from(element.querySelectorAll('.cmp-breadcrumb__item, li'));

  const cells = [];
  items.forEach((item) => {
    const link = item.querySelector('a');
    if (link) {
      // Ancestor crumb: keep the anchor (href + label). Normalize label text.
      const label = (link.textContent || '').trim();
      const a = document.createElement('a');
      a.href = link.getAttribute('href');
      a.textContent = label;
      cells.push([a]);
    } else {
      // Active/current crumb: plain text label.
      const label = (item.textContent || '').trim();
      if (label) cells.push([label]);
    }
  });

  // Empty-block guard: nothing to build.
  if (cells.length === 0) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'breadcrumbs', cells });
  element.replaceWith(block);
}
