/* eslint-disable */
/* global WebImporter */
/**
 * Parser for cards-teaser.
 * Base: cards (2 columns; first row block name, each subsequent row = 1 card).
 * Source: wknd.site image list (div.image-list.list > ul.cmp-image-list).
 * Generated by import-parser sub-agent.
 *
 * Library structure (Cards):
 *   Cell 1: Image (mandatory)
 *   Cell 2: Text content — Title (heading + link) + Description
 */
export default function parse(element, { document }) {
  const items = Array.from(element.querySelectorAll('.cmp-image-list__item, li'));

  const cells = [];
  items.forEach((item) => {
    const img = item.querySelector('img');
    const titleLink = item.querySelector('.cmp-image-list__item-title-link, a');
    const titleText = item.querySelector('.cmp-image-list__item-title');
    const description = item.querySelector('.cmp-image-list__item-description');

    // Skip items with no meaningful content.
    if (!img && !titleLink && !titleText && !description) return;

    // Image cell.
    const imageCell = img || '';

    // Text cell: title as a linked heading, then description.
    const textCell = [];
    const label = (titleText ? titleText.textContent : (titleLink ? titleLink.textContent : '')).trim();
    if (label) {
      const heading = document.createElement('h3');
      const href = titleLink ? titleLink.getAttribute('href') : null;
      if (href) {
        const a = document.createElement('a');
        a.href = href;
        a.textContent = label;
        heading.append(a);
      } else {
        heading.textContent = label;
      }
      textCell.push(heading);
    }
    if (description) {
      const p = document.createElement('p');
      p.textContent = (description.textContent || '').trim();
      textCell.push(p);
    }

    cells.push([imageCell, textCell]);
  });

  // Empty-block guard.
  if (cells.length === 0) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'cards-teaser', cells });
  element.replaceWith(block);
}
