/* eslint-disable */
/* global WebImporter */
/**
 * Parser for cards-profile.
 * Base: cards (2 columns; first row block name, each subsequent row = 1 card).
 * Source: wknd.site contributor experience fragment
 *   (section.experiencefragment.cmp-experience-fragment--contributor).
 * Generated by import-parser sub-agent.
 *
 * This variant is a single contributor profile per instance:
 *   Cell 1: portrait image (mandatory)
 *   Cell 2: name (heading), role (subheading), social CTA links
 */
export default function parse(element, { document }) {
  const img = element.querySelector('.image img, img');
  // Name: first title (h3), role: second title (h5).
  const titles = Array.from(element.querySelectorAll('.cmp-title__text, .title .cmp-title__text'));
  const name = titles[0] || null;
  const role = titles[1] || null;
  const socialLinks = Array.from(element.querySelectorAll('.button a.cmp-button, .cmp-button'));

  // Empty-block guard.
  if (!img && !name && !role) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const imageCell = img || '';

  const textCell = [];
  if (name) {
    const h = document.createElement('h3');
    h.textContent = (name.textContent || '').trim();
    textCell.push(h);
  }
  if (role) {
    const h = document.createElement('h5');
    h.textContent = (role.textContent || '').trim();
    textCell.push(h);
  }
  socialLinks.forEach((link) => {
    const href = link.getAttribute('href');
    if (!href) return;
    // Prefer the visible label span; fall back to link text.
    const labelEl = link.querySelector('.cmp-button__text');
    const label = (labelEl ? labelEl.textContent : link.textContent || '').trim();
    const a = document.createElement('a');
    a.href = href;
    a.textContent = label;
    textCell.push(a);
  });

  const cells = [[imageCell, textCell]];

  const block = WebImporter.Blocks.createBlock(document, { name: 'cards-profile', cells });
  element.replaceWith(block);
}
