/* eslint-disable */
/* global WebImporter */
/**
 * Parser for carousel-hero.
 * Base: carousel (2 columns; first row block name, each subsequent row = 1 slide).
 * Source: wknd.site hero carousel (div.carousel.panelcontainer > .cmp-carousel),
 *   each slide is a teaser (title + description + CTA + image).
 * Generated by import-parser sub-agent.
 *
 * Library structure (Carousel):
 *   Cell 1: Image (mandatory)
 *   Cell 2: Text content — Title (heading), Description, Call-to-Action
 */
export default function parse(element, { document }) {
  const slides = Array.from(element.querySelectorAll('.cmp-carousel__item'));

  const cells = [];
  slides.forEach((slide) => {
    const img = slide.querySelector('.cmp-teaser__image img, .cmp-image img, img');
    const heading = slide.querySelector('.cmp-teaser__title, h1, h2, h3, [class*="title"]');
    const description = slide.querySelector('.cmp-teaser__description, [class*="description"]');
    const cta = slide.querySelector('.cmp-teaser__action-link, .cmp-teaser__action-container a');

    // Skip empty slides.
    if (!img && !heading && !description) return;

    const imageCell = img || '';

    const textCell = [];
    if (heading) {
      const h = document.createElement('h2');
      h.textContent = (heading.textContent || '').trim();
      textCell.push(h);
    }
    if (description) {
      const p = document.createElement('p');
      p.textContent = (description.textContent || '').trim();
      textCell.push(p);
    }
    if (cta && cta.getAttribute('href')) {
      const a = document.createElement('a');
      a.href = cta.getAttribute('href');
      a.textContent = (cta.textContent || '').trim();
      textCell.push(a);
    }

    cells.push([imageCell, textCell.length ? textCell : '']);
  });

  // Empty-block guard.
  if (cells.length === 0) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'carousel-hero', cells });
  element.replaceWith(block);
}
