/* eslint-disable */
/* global WebImporter */
/**
 * Parser for carousel-gallery.
 * Base: carousel (2 columns; first row block name, each subsequent row = 1 slide).
 * Source: wknd.site mini carousel (div.carousel.panelcontainer > .cmp-carousel).
 * Generated by import-parser sub-agent.
 *
 * Library structure (Carousel):
 *   Cell 1: Image (mandatory)
 *   Cell 2: Text content (optional) — Title, Description, CTA
 * This is an image-only gallery, so the text cell is empty but kept for the
 * fixed 2-column structure.
 */
export default function parse(element, { document }) {
  const slides = Array.from(element.querySelectorAll('.cmp-carousel__item'));

  const cells = [];
  slides.forEach((slide) => {
    const img = slide.querySelector('.cmp-image img, img');
    if (!img) return;

    // Optional text content within the slide (title / description / CTA).
    const heading = slide.querySelector('.cmp-teaser__title, h1, h2, h3, [class*="title"]');
    const description = slide.querySelector('.cmp-teaser__description, [class*="description"]');
    const cta = slide.querySelector('.cmp-teaser__action-link, a');

    const textCell = [];
    if (heading) {
      const h = document.createElement('h3');
      h.textContent = (heading.textContent || '').trim();
      textCell.push(h);
    }
    if (description) {
      const p = document.createElement('p');
      p.textContent = (description.textContent || '').trim();
      textCell.push(p);
    }
    if (cta && cta.getAttribute('href')) {
      const a = document.createElement('a');
      a.href = cta.getAttribute('href');
      a.textContent = (cta.textContent || '').trim();
      textCell.push(a);
    }

    cells.push([img, textCell.length ? textCell : '']);
  });

  // Empty-block guard.
  if (cells.length === 0) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'carousel-gallery', cells });
  element.replaceWith(block);
}
