/* eslint-disable */
/* global WebImporter */
/**
 * Parser for hero-banner.
 * Base: hero (1 column, up to 3 rows: name row, background image row, content row).
 * Source: wknd.site teaser blocks (div.teaser.cmp-teaser--hero).
 * Generated by import-parser sub-agent.
 *
 * Library structure (Hero):
 *   Row 2 (single cell): Background Image (optional)
 *   Row 3 (single cell): Title (heading), Subheading, Call-to-Action
 */
export default function parse(element, { document }) {
  // Background/hero image.
  const image = element.querySelector('.cmp-teaser__image img, img[class*="image"], img');

  // Text content.
  const heading = element.querySelector('.cmp-teaser__title, h1, h2, h3, [class*="title"]');
  const description = element.querySelector('.cmp-teaser__description, [class*="description"], p');
  const ctaLinks = Array.from(
    element.querySelectorAll('.cmp-teaser__action-link, .cmp-teaser__action-container a'),
  );

  // Empty-block guard.
  if (!image && !heading && !description) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const cells = [];

  // Row 2: background image (optional).
  if (image) cells.push([image]);

  // Row 3: text content in a single cell.
  const contentCell = [];
  if (heading) {
    const h = document.createElement('h2');
    h.textContent = (heading.textContent || '').trim();
    contentCell.push(h);
  }
  if (description) contentCell.push(description);
  ctaLinks.forEach((cta) => {
    const a = document.createElement('a');
    a.href = cta.getAttribute('href');
    a.textContent = (cta.textContent || '').trim();
    contentCell.push(a);
  });
  cells.push([contentCell]);

  const block = WebImporter.Blocks.createBlock(document, { name: 'hero-banner', cells });
  element.replaceWith(block);
}
