/* eslint-disable */
/* global WebImporter */
/**
 * Parser for table-specs.
 * Base: table (multiple columns/rows; first row is block name).
 * Source: wknd.site content fragment spec list (dl.cmp-contentfragment__elements).
 * Generated by import-parser sub-agent.
 *
 * Each spec element (Activity, Adventure Type, Trip Length, Group Size,
 * Difficulty, Price) becomes one 2-column row: label cell + value cell.
 * The instance element is div.contentfragment.cmp-contentfragment--elements,
 * which wraps the article holding the dt/dd spec pairs.
 */
export default function parse(element, { document }) {
  // Each spec is a dt (label) / dd (value) pair grouped in a wrapper div.
  const groups = Array.from(element.querySelectorAll('.cmp-contentfragment__element'));

  const cells = [];

  if (groups.length) {
    groups.forEach((group) => {
      const dt = group.querySelector('dt, .cmp-contentfragment__element-title');
      const dd = group.querySelector('dd, .cmp-contentfragment__element-value');
      const label = dt ? (dt.textContent || '').trim() : '';
      const value = dd ? (dd.textContent || '').trim() : '';
      if (label || value) cells.push([label, value]);
    });
  } else {
    // Fallback: iterate dt/dd pairs directly.
    const dts = Array.from(element.querySelectorAll('dt'));
    dts.forEach((dt) => {
      const dd = dt.nextElementSibling && dt.nextElementSibling.tagName === 'DD'
        ? dt.nextElementSibling
        : null;
      const label = (dt.textContent || '').trim();
      const value = dd ? (dd.textContent || '').trim() : '';
      if (label || value) cells.push([label, value]);
    });
  }

  // Empty-block guard.
  if (cells.length === 0) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'table-specs', cells });
  element.replaceWith(block);
}
