/* eslint-disable */
/* global WebImporter */
/**
 * Parser for tabs-detail.
 * Base: tabs (2 columns; first row block name, each subsequent row = 1 tab).
 * Source: wknd.site tabs (div.tabs.panelcontainer > .cmp-tabs), with a
 *   tablist of labels (Overview / Itinerary / What to Bring) and matching
 *   tabpanels containing content-fragment body copy.
 * Generated by import-parser sub-agent.
 *
 * Library structure (Tabs):
 *   Cell 1: Tab Label (mandatory)
 *   Cell 2: Tab Content (mandatory)
 */
export default function parse(element, { document }) {
  // Tab labels (ordered) and their content panels (ordered) pair by index.
  const labels = Array.from(element.querySelectorAll('.cmp-tabs__tablist .cmp-tabs__tab, .cmp-tabs__tab'));
  const panels = Array.from(element.querySelectorAll('.cmp-tabs__tabpanel'));

  const cells = [];
  labels.forEach((labelEl, i) => {
    const label = (labelEl.textContent || '').trim();
    const panel = panels[i];

    // Content cell: prefer the content-fragment body; fall back to the panel.
    let contentCell = '';
    if (panel) {
      const cf = panel.querySelector('.cmp-contentfragment__elements');
      contentCell = cf || panel;
    }

    if (label || contentCell) cells.push([label, contentCell || '']);
  });

  // Empty-block guard.
  if (cells.length === 0) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'tabs-detail', cells });
  element.replaceWith(block);
}
