/* eslint-disable */
/* global WebImporter */
/**
 * Parser for tabs-filter.
 * Base: tabs (2 columns; first row block name, each subsequent row = 1 tab).
 * Source: wknd.site category filter tabs (div.tabs.panelcontainer > .cmp-tabs),
 *   a tablist of category labels (All / Climbing / Cycling / ...) with each
 *   tabpanel wrapping an image-list card grid.
 * Generated by import-parser sub-agent.
 *
 * Library structure (Tabs):
 *   Cell 1: Tab Label (category)
 *   Cell 2: Tab Content (the card grid for that category)
 */
export default function parse(element, { document }) {
  const labels = Array.from(element.querySelectorAll('.cmp-tabs__tablist .cmp-tabs__tab, .cmp-tabs__tab'));
  const panels = Array.from(element.querySelectorAll('.cmp-tabs__tabpanel'));

  const cells = [];
  labels.forEach((labelEl, i) => {
    const label = (labelEl.textContent || '').trim();
    const panel = panels[i];

    // Content cell: the card grid (image-list) for this category, else the panel.
    let contentCell = '';
    if (panel) {
      const grid = panel.querySelector('.cmp-image-list, .image-list');
      contentCell = grid || panel;
    }

    if (label || contentCell) cells.push([label, contentCell || '']);
  });

  // Empty-block guard.
  if (cells.length === 0) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'tabs-filter', cells });
  element.replaceWith(block);
}
